# Netlify Configuration for BOOM Card Frontend

[build]
  # Build command without TypeScript (temporary fix)
  command = "npm install --legacy-peer-deps && npm run build"
  
  # Next.js build output directory
  publish = ".next"

# Environment variables needed for build
[build.environment]
  # Node and npm configuration
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NODE_ENV = "production"
  
  # Next.js configuration
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_URL = "https://boom-card.onrender.com/api"
  
  # Build flags
  NPM_FLAGS = "--legacy-peer-deps"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Next.js Plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = ".next"
  autoLaunch = true

# Context-specific settings
[context.production]
  environment = { NODE_ENV = "production" }
  
[context.deploy-preview]
  environment = { NODE_ENV = "development" }
  
[context.branch-deploy]
  environment = { NODE_ENV = "development" }