# Netlify Configuration for BOOM Card Platform

[build]
  # Base directory for the frontend
  base = "frontend"
  
  # Build command for Next.js with legacy peer deps and devDependencies
  command = "npm install --legacy-peer-deps && npm run build"
  
  # The @netlify/plugin-nextjs will handle the publish directory automatically
  # Do not set publish directory for Next.js apps

# Environment variables needed for build
[build.environment]
  # Ensure Next.js optimizations are enabled
  NEXT_TELEMETRY_DISABLED = "1"
  # Set Node version to LTS (18.18.0 or higher required by dependencies)
  NODE_VERSION = "20"
  # Install devDependencies during build
  NODE_ENV = "development"
  # Additional npm flags
  NPM_FLAGS = "--legacy-peer-deps"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Plugin to handle Next.js deployment
[[plugins]]
  package = "@netlify/plugin-nextjs"

[plugins.inputs]
  # Ensure the plugin handles the Next.js build correctly
  enable = true

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  autoLaunch = true

# Context-specific settings
[context.production]
  environment = { NODE_ENV = "production" }
  
[context.deploy-preview]
  environment = { NODE_ENV = "development" }
  
[context.branch-deploy]
  environment = { NODE_ENV = "development" }