# Netlify Configuration for BOOM Card Platform

[build]
  # Base directory for the frontend
  base = "frontend"
  
  # Build command for Next.js with legacy peer deps and cache clear
  command = "rm -rf .next node_modules/.cache .swc && npm ci --legacy-peer-deps && NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 npm run build"
  
  # Next.js build output directory
  publish = ".next"
  
  # Explicitly disable static export
  [build.processing]
    skip = true

# Environment variables needed for build
[build.environment]
  # Ensure Next.js optimizations are enabled
  NEXT_TELEMETRY_DISABLED = "1"
  # Set Node version to match requirements
  NODE_VERSION = "18.18.0"
  # Additional npm flags
  NPM_FLAGS = "--legacy-peer-deps"
  # API URL for production - using mock for now
  NEXT_PUBLIC_API_URL = "/api/mock"
  # Disable external services for now
  NEXT_PUBLIC_DISABLE_EXTERNAL_SERVICES = "true"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Plugin to handle Next.js deployment
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = ".next"
  autoLaunch = true

# Context-specific settings
[context.production]
  environment = { NODE_ENV = "production" }
  
[context.deploy-preview]
  environment = { NODE_ENV = "development" }
  
[context.branch-deploy]
  environment = { NODE_ENV = "development" }