apiVersion: v1
kind: ConfigMap
metadata:
  name: boom-card-config
  namespace: boom-card
data:
  # Application Configuration
  NODE_ENV: "production"
  APP_NAME: "BOOM Card"
  APP_VERSION: "1.0.0"
  APP_PORT: "3000"
  API_PORT: "5000"
  
  # URLs and Domains
  APP_URL: "https://boomcard.bg"
  API_URL: "https://api.boomcard.bg"
  CDN_URL: "https://cdn.boomcard.bg"
  ADMIN_URL: "https://admin.boomcard.bg"
  PARTNER_URL: "https://partner.boomcard.bg"
  
  # Database Configuration
  DB_HOST: "postgres-service.boom-card.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "boomcard"
  DB_SSL: "true"
  DB_POOL_MIN: "2"
  DB_POOL_MAX: "10"
  
  # Redis Configuration
  REDIS_HOST: "redis-service.boom-card.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_CACHE_TTL: "3600"
  REDIS_SESSION_TTL: "86400"
  
  # Email Configuration
  SMTP_HOST: "smtp.sendgrid.net"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  EMAIL_FROM: "noreply@boomcard.bg"
  EMAIL_SUPPORT: "support@boomcard.bg"
  
  # Storage Configuration
  STORAGE_TYPE: "s3"
  S3_REGION: "eu-central-1"
  S3_BUCKET: "boom-card-assets"
  S3_ENDPOINT: "https://s3.eu-central-1.amazonaws.com"
  
  # Payment Configuration
  PAYMENT_PROVIDER: "stripe"
  STRIPE_WEBHOOK_ENDPOINT: "/api/webhooks/stripe"
  SUBSCRIPTION_TRIAL_DAYS: "7"
  SUBSCRIPTION_GRACE_PERIOD_DAYS: "3"
  
  # Security Configuration
  SESSION_NAME: "boom_card_session"
  SESSION_SECURE: "true"
  SESSION_HTTP_ONLY: "true"
  SESSION_SAME_SITE: "lax"
  CORS_ALLOWED_ORIGINS: "https://boomcard.bg,https://www.boomcard.bg,https://admin.boomcard.bg,https://partner.boomcard.bg"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  
  # Localization
  DEFAULT_LOCALE: "bg"
  SUPPORTED_LOCALES: "bg,en"
  TIMEZONE: "Europe/Sofia"
  
  # Analytics Configuration
  ANALYTICS_ENABLED: "true"
  GA_TRACKING_ID: "UA-XXXXXXXXX-X"
  MIXPANEL_PROJECT_TOKEN: ""
  
  # Map Configuration
  MAP_PROVIDER: "mapbox"
  MAP_DEFAULT_CENTER_LAT: "42.6977"
  MAP_DEFAULT_CENTER_LNG: "23.3219"
  MAP_DEFAULT_ZOOM: "12"
  
  # QR Code Configuration
  QR_CODE_SIZE: "300"
  QR_CODE_MARGIN: "4"
  QR_CODE_ERROR_CORRECTION: "M"
  
  # Search Configuration
  SEARCH_MIN_QUERY_LENGTH: "2"
  SEARCH_MAX_RESULTS: "50"
  SEARCH_DEFAULT_RADIUS_KM: "10"
  
  # File Upload Configuration
  MAX_FILE_SIZE_MB: "10"
  ALLOWED_IMAGE_TYPES: "image/jpeg,image/png,image/webp"
  IMAGE_OPTIMIZATION_QUALITY: "85"
  
  # Notification Configuration
  PUSH_NOTIFICATION_ENABLED: "true"
  SMS_NOTIFICATION_ENABLED: "true"
  EMAIL_NOTIFICATION_ENABLED: "true"
  
  # Partner Configuration
  PARTNER_ONBOARDING_STEPS: "business_info,locations,offers,payment,review"
  PARTNER_COMMISSION_PERCENTAGE: "5"
  PARTNER_PAYOUT_MINIMUM: "50"
  PARTNER_PAYOUT_FREQUENCY: "monthly"
  
  # Consumer Configuration
  CONSUMER_REFERRAL_ENABLED: "true"
  CONSUMER_REFERRAL_REWARD_DAYS: "30"
  CONSUMER_POINTS_ENABLED: "true"
  CONSUMER_POINTS_PER_TRANSACTION: "10"
  
  # Monitoring Configuration
  MONITORING_ENABLED: "true"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  HEALTH_CHECK_PATH: "/health"
  READY_CHECK_PATH: "/ready"
  
  # Feature Flags
  FEATURE_MOBILE_APP: "true"
  FEATURE_SOCIAL_LOGIN: "true"
  FEATURE_ADVANCED_ANALYTICS: "true"
  FEATURE_AI_RECOMMENDATIONS: "true"
  FEATURE_PARTNER_API: "true"
  FEATURE_MULTI_LOCATION: "true"
  FEATURE_DYNAMIC_PRICING: "false"
  FEATURE_LOYALTY_PROGRAM: "true"
  
  # Integration Configuration
  POS_INTEGRATION_ENABLED: "true"
  POS_WEBHOOK_TIMEOUT_MS: "5000"
  POS_RETRY_ATTEMPTS: "3"
  POS_RETRY_DELAY_MS: "1000"
  
  # Cache Configuration
  CACHE_ENABLED: "true"
  CACHE_TTL_PARTNERS: "300"
  CACHE_TTL_OFFERS: "600"
  CACHE_TTL_CATEGORIES: "3600"
  CACHE_TTL_STATIC_CONTENT: "86400"
  
  # Business Rules
  OFFER_MIN_DISCOUNT_PERCENTAGE: "5"
  OFFER_MAX_DISCOUNT_PERCENTAGE: "50"
  OFFER_VALIDATION_REQUIRED: "true"
  TRANSACTION_EXPIRY_MINUTES: "15"
  QR_CODE_EXPIRY_MINUTES: "5"
