import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'bg';

;
}

const translations= {
  // Navigation
  'nav.home': { en, bg,
  'nav.partners': { en, bg,
  'nav.plans': { en, bg,
  'nav.dashboard': { en, bg,
  'nav.profile': { en, bg,
  'nav.getStarted': { en, bg,
  'nav.accountSettings': { en, bg,
  
  // Hero Section - Homepage
  'hero.badge': { en, bg,
  'hero.title1': { en, bg,
  'hero.title2': { en, bg,
  'hero.subtitle': { en,000+ members enjoying exclusive access to Bulgaria\'s finest restaurants, luxury hotels, premium spas, and entertainment venues with discounts up to 40%.', bg,000+ членове, които се радват на ексклузивен достъп до най-добрите ресторанти, луксозни хотели, премиум спа центрове и места за забавление в България с отстъпки до 40%.' },
  'hero.cta.start': { en, bg,
  'hero.cta.demo': { en, bg,
  'hero.trust.verified': { en, bg,
  'hero.trust.instant': { en, bg,
  'hero.trust.noFees': { en, bg,
  
  // Stats Section
  'stats.title': { en, bg,
  'stats.subtitle': { en, bg,
  'stats.activePartners': { en, bg,
  'stats.totalSavings': { en, bg,
  'stats.happyMembers': { en, bg,
  'stats.cities': { en, bg,
  
  // Categories Section
  'categories.badge': { en, bg,
  'categories.title': { en, bg,
  'categories.subtitle': { en, discover hand-picked experiences that define premium lifestyle', bg, открийте внимателно подбрани преживявания, които определят премиум начина на живот' },
  'categories.fineDining': { en, bg,
  'categories.fineDiningDesc': { en, bg,
  'categories.luxuryHotels': { en, bg,
  'categories.luxuryHotelsDesc': { en, bg,
  'categories.wellness': { en, bg,
  'categories.wellnessDesc': { en, bg,
  'categories.entertainment': { en, bg,
  'categories.entertainmentDesc': { en, bg,
  'categories.upTo': { en, bg,
  'categories.explore': { en, bg,
  
  // Features Section
  'features.badge': { en, bg,
  'features.title1': { en, bg,
  'features.title2': { en, bg,
  'features.subtitle': { en, bg, за да предостави несравнима стойност' },
  'features.instantAccess': { en, bg,
  'features.instantAccessDesc': { en, bg,
  'features.securePayments': { en, bg,
  'features.securePaymentsDesc': { en, bg,
  'features.premiumPartners': { en, bg,
  'features.premiumPartnersDesc': { en, bg,
  'features.mobileFirst': { en, bg,
  'features.mobileFirstDesc': { en, bg,
  'features.learnMore': { en, bg,
  
  // Testimonials Section
  'testimonials.badge': { en, bg,
  'testimonials.title': { en,000+ Members Across Bulgaria', bg,000+ членове в цяла България' },
  'testimonials.subtitle': { en, bg, които са трансформирали начина си на живот с BOOM Card' },
  'testimonials.elena.name': { en, bg,
  'testimonials.elena.role': { en, bg,
  'testimonials.elena.content': { en, bg,
  'testimonials.dimitar.name': { en, bg,
  'testimonials.dimitar.role': { en, bg,
  'testimonials.dimitar.content': { en, bg,
  'testimonials.maria.name': { en, bg,
  'testimonials.maria.role': { en, bg,
  'testimonials.maria.content': { en, bg,
  'testimonials.leaveReview': { en, bg,
  'testimonials.writeReview': { en, bg,
  
  // CTA Section
  'cta.title1': { en, bg,
  'cta.title2': { en, bg,
  'cta.subtitle': { en,000+ smart savers who are already enjoying exclusive access to Bulgaria\'s finest establishments with savings up to 40%.', bg,000+ интелигентни спестители, които вече се радват на ексклузивен достъп до най-добрите заведения в България със спестявания до 40%.' },
  'cta.choosePlan': { en, bg,
  'cta.downloadApp': { en, bg,
  'cta.memberSavings': { en, bg,
  'cta.premiumPartners': { en, bg,
  'cta.activeMembers': { en, bg,
  'cta.memberRating': { en, bg,
  
  // Footer
  'footer.description': { en, bg, свързваща ви с ексклузивни преживявания в най-добрите заведения на страната.' },
  'footer.premiumCategories': { en, bg,
  'footer.fineDiningRestaurants': { en, bg,
  'footer.luxuryHotelsResorts': { en, bg,
  'footer.premiumSpasWellness': { en, bg,
  'footer.entertainmentEvents': { en, bg,
  'footer.exclusiveExperiences': { en, bg,
  'footer.company': { en, bg,
  'footer.aboutBoomCard': { en, bg,
  'footer.partnerWithUs': { en, bg,
  'footer.memberSupport': { en, bg,
  'footer.contactLocations': { en, bg,
  'footer.pressMedia': { en, bg,
  'footer.getTheApp': { en, bg,
  'footer.downloadOn': { en, bg,
  'footer.appStore': { en, bg,
  'footer.getItOn': { en, bg,
  'footer.googlePlay': { en, bg,
  'footer.securePrivate': { en, bg,
  'footer.instantAccess': { en, bg,
  'footer.rights': { en, bg,
  'footer.privacyPolicy': { en, bg,
  'footer.termsOfService': { en, bg,
  'footer.allSystemsOperational': { en, bg,
  'footer.madeInBulgaria': { en, bg,
  
  // Common
  'common.learnMore': { en, bg,
  'common.viewDetails': { en, bg,
  'common.save': { en, bg,
  'common.saved': { en, bg,
  'common.off': { en, bg,
  
  // Subscriptions Page
  'subscriptions.hero.badge': { en,000+ Happy Members', bg,000+ доволни членове' },
  'subscriptions.hero.title1': { en, bg,
  'subscriptions.hero.title2': { en, bg,
  'subscriptions.hero.subtitle': { en, luxury hotels, premium spas, and entertainment venues with discounts up to 40%.', bg, луксозни хотели, премиум спа центрове и места за забавление в България с отстъпки до 40%.' },
  'subscriptions.billing.monthly': { en, bg,
  'subscriptions.billing.yearly': { en, bg,
  'subscriptions.billing.save25': { en, bg,
  'subscriptions.trust.moneyBack': { en, bg,
  'subscriptions.trust.cancelAnytime': { en, bg,
  'subscriptions.trust.instantActivation': { en, bg,
  
  // Plan Names
  'plans.essential.name': { en, bg,
  'plans.essential.description': { en, bg,
  'plans.premium.name': { en, bg,
  'plans.premium.description': { en, bg,
  'plans.vip.name': { en, bg,
  'plans.vip.description': { en, bg,
  
  // Account Settings
  'accountSettings.title': { en, bg,
  'accountSettings.subtitle': { en, bg,
  'accountSettings.personal': { en, bg,
  'accountSettings.security': { en, bg,
  'accountSettings.notifications': { en, bg,
  'accountSettings.billing': { en, bg,
  'accountSettings.privacy': { en, bg,
  'accountSettings.personalInfo': { en, bg,
  'accountSettings.firstName': { en, bg,
  'accountSettings.lastName': { en, bg,
  'accountSettings.email': { en, bg,
  'accountSettings.phone': { en, bg,
  'accountSettings.saveChanges': { en, bg,
  'accountSettings.securitySettings': { en, bg,
  'accountSettings.changePassword': { en, bg,
  'accountSettings.currentPassword': { en, bg,
  'accountSettings.newPassword': { en, bg,
  'accountSettings.confirmPassword': { en, bg,
  'accountSettings.updatePassword': { en, bg,
  'accountSettings.twoFactorAuth': { en, bg,
  'accountSettings.twoFactorDesc': { en, bg,
  'accountSettings.enable2FA': { en, bg,
  'accountSettings.notificationPreferences': { en, bg,
  'accountSettings.emailAlerts': { en, bg,
  'accountSettings.emailAlertsDesc': { en, bg,
  'accountSettings.smsAlerts': { en, bg,
  'accountSettings.smsAlertsDesc': { en, bg,
  'accountSettings.pushNotifications': { en, bg,
  'accountSettings.pushNotificationsDesc': { en, bg,
  'accountSettings.marketingEmails': { en, bg,
  'accountSettings.marketingEmailsDesc': { en, bg,
  'accountSettings.savePreferences': { en, bg,
  'accountSettings.billingPayment': { en, bg,
  'accountSettings.currentPlan': { en, bg,
  'accountSettings.nextBilling': { en, bg,
  'accountSettings.month': { en, bg,
  'accountSettings.changePlan': { en, bg,
  'accountSettings.paymentMethod': { en, bg,
  'accountSettings.expires': { en, bg,
  'accountSettings.update': { en, bg,
  'accountSettings.billingHistory': { en, bg,
  'accountSettings.downloadInvoice': { en, bg,
  'accountSettings.privacySettings': { en, bg,
  'accountSettings.dataPrivacy': { en, bg,
  'accountSettings.dataPrivacyDesc': { en, bg,
  'accountSettings.downloadData': { en, bg,
  'accountSettings.deleteAccount': { en, bg,
  'accountSettings.connectedAccounts': { en, bg,
  'accountSettings.connect': { en, bg,
  'accountSettings.connected': { en, bg,

  // How It Works page
  'howItWorks.hero.title': { en, bg,
  'howItWorks.hero.subtitle': { en, bg,
  'howItWorks.step1.title': { en, bg,
  'howItWorks.step1.description': { en, bg,
  'howItWorks.step2.title': { en, bg,
  'howItWorks.step2.description': { en, hotels, spas, and entertainment venues.', bg, хотели, спа центрове и места за развлечение.' },
  'howItWorks.step3.title': { en, bg,
  'howItWorks.step3.description': { en, bg, за да отключите отстъпката.' },
  'howItWorks.step4.title': { en, bg,
  'howItWorks.step4.description': { en, bg,
  'howItWorks.faq.title': { en, bg,
  'howItWorks.faq.q1': { en, bg,
  'howItWorks.faq.a1': { en, hotels, spas, entertainment venues, and retail stores across Bulgaria. Our partner network is constantly growing!', bg, хотели, спа центрове, места за развлечение и магазини в цяла България. Нашата партньорска мрежа непрекъснато расте!' },
  'howItWorks.faq.q2': { en, bg,
  'howItWorks.faq.a2': { en, depending on the partner and offer. Most members save their annual membership fee within the first month!', bg, в зависимост от партньора и офертата. Повечето членове спестяват годишната си такса за членство още през първия месец!' },
  'howItWorks.faq.q3': { en, bg,
  'howItWorks.faq.a3': { en, each with their own QR code. Individual and Standard plans are for personal use only.', bg, всеки със собствен QR код. Индивидуалните и стандартните планове са само за лична употреба.' },
  'howItWorks.cta.title': { en, bg,
  'howItWorks.cta.subtitle': { en, bg, които се наслаждават на ексклузивни отстъпки' },
  'howItWorks.cta.button': { en, bg,

  // Help Center page
  'help.hero.title': { en, bg,
  'help.hero.subtitle': { en, bg,
  'help.searchPlaceholder': { en, bg,
  'help.categories.all': { en, bg,
  'help.categories.account': { en, bg,
  'help.categories.billing': { en, bg,
  'help.categories.usage': { en, bg,
  'help.categories.partners': { en, bg,
  'help.categories.technical': { en, bg,
  'help.popular': { en, bg,
  'help.readMore': { en, bg,
  'help.noResults': { en, bg,
  'help.articles.resetPassword.title': { en, bg,
  'help.articles.resetPassword.content': { en, bg,
  'help.articles.changeSubscription.title': { en, bg,
  'help.articles.changeSubscription.content': { en, bg,
  'help.articles.useQR.title': { en, bg,
  'help.articles.useQR.content': { en, tap on "My Card" to display your QR code. Show it to the merchant at checkout.', bg, докоснете „Моята карта", за да се покаже вашият QR код. Покажете го на търговеца при плащане.' },
  'help.articles.findPartners.title': { en, bg,
  'help.articles.findPartners.content': { en, bg,
  'help.articles.appNotWorking.title': { en, bg,
  'help.articles.appNotWorking.content': { en, contact support.', bg, свържете се с поддръжката.' },
  'help.articles.cancelSubscription.title': { en, bg,
  'help.articles.cancelSubscription.content': { en, bg,
  'help.contact.title': { en, bg,
  'help.contact.subtitle': { en, bg, за да ви помогне' },
  'help.contact.email': { en, bg,
  'help.contact.phone': { en, bg,
  'help.contact.hours': { en, bg,

  // Contact page
  'contact.hero.title': { en, bg,
  'contact.hero.subtitle': { en, bg, за да помогнем и да отговорим на всички ваши въпроси' },
  'contact.form.title': { en, bg,
  'contact.form.name': { en, bg,
  'contact.form.email': { en, bg,
  'contact.form.subject': { en, bg,
  'contact.form.subjects.general': { en, bg,
  'contact.form.subjects.support': { en, bg,
  'contact.form.subjects.billing': { en, bg,
  'contact.form.subjects.partnership': { en, bg,
  'contact.form.subjects.feedback': { en, bg,
  'contact.form.message': { en, bg,
  'contact.form.send': { en, bg,
  'contact.form.success': { en, bg, че се свързахте с нас! Ще се свържем с вас скоро.' },
  'contact.info.title': { en, bg,
  'contact.info.address.title': { en, bg,
  'contact.info.phone.title': { en, bg,
  'contact.info.phone.hours': { en, 9AM - 6PM EET', bg, 9,
  'contact.info.email.title': { en, bg,
  'contact.info.email.general': { en, bg,
  'contact.info.email.support': { en, bg,
  'contact.info.email.partners': { en, bg,
  'contact.map.title': { en, bg,
  'contact.map.placeholder': { en, bg,
  'contact.faq.title': { en, bg,
  'contact.faq.subtitle': { en, bg,
  'contact.faq.button': { en, bg,

  // FAQ page
  'faq.hero.title': { en, bg,
  'faq.hero.subtitle': { en, bg, което трябва да знаете за BOOM Card' },
  'faq.categories.all': { en, bg,
  'faq.categories.general': { en, bg,
  'faq.categories.membership': { en, bg,
  'faq.categories.usage': { en, bg,
  'faq.categories.billing': { en, bg,
  'faq.categories.partners': { en, bg,
  'faq.items.whatIs.q': { en, bg,
  'faq.items.whatIs.a': { en, hotels, spas, and entertainment venues. With savings of 10-50% at each partner location, your membership pays for itself quickly.', bg, която ви дава ексклузивен достъп до отстъпки в стотици ресторанти, хотели, спа центрове и места за развлечение. Със спестявания от 10-50% във всяка партньорска локация, членството ви се изплаща бързо.' },
  'faq.items.howWorks.q': { en, bg,
  'faq.items.howWorks.a': { en, bg, за да получите отстъпката си. Отстъпката се прилага незабавно към сметката ви.' },
  'faq.items.plans.q': { en, bg,
  'faq.items.plans.a': { en), Standard (29 BGN/month with more partners), and Family (49 BGN/month for up to 5 members). All plans include unlimited use at all partner locations.', bg), Стандартен (29 лв./месец с повече партньори) и Семеен (49 лв./месец за до 5 членове). Всички планове включват неограничена употреба във всички партньорски локации.' },
  'faq.items.cancel.q': { en, bg,
  'faq.items.cancel.a': { en, you can cancel your membership at any time from your account settings. Your access will continue until the end of your current billing period.', bg, можете да отмените членството си по всяко време от настройките на акаунта. Достъпът ви ще продължи до края на текущия период на фактуриране.' },
  'faq.items.multipleUse.q': { en, bg,
  'faq.items.multipleUse.a': { en, bg,
  'faq.items.shareCard.q': { en, bg,
  'faq.items.shareCard.a': { en, consider our Family Plan which allows up to 5 members.', bg, помислете за нашия Семеен план, който позволява до 5 членове.' },
  'faq.items.paymentMethods.q': { en, bg,
  'faq.items.paymentMethods.a': { en, Mastercard, American Express) as well as PayPal. All payments are processed securely through Stripe.', bg, Mastercard, American Express), както и PayPal. Всички плащания се обработват сигурно чрез Stripe.' },
  'faq.items.changePlan.q': { en, bg,
  'faq.items.changePlan.a': { en, you can upgrade or downgrade your plan at any time from your account settings. Changes take effect at the start of your next billing cycle.', bg, можете да надградите или понижите плана си по всяко време от настройките на акаунта. Промените влизат в сила в началото на следващия период на фактуриране.' },
  'faq.items.findPartners.q': { en, bg,
  'faq.items.findPartners.a': { en, category, or name. You can also enable location services for personalized recommendations nearby.', bg, за да намерите партньори по местоположение, категория или име. Можете също да активирате услугите за местоположение за персонализирани препоръки наблизо.' },
  'faq.items.becomePartner.q': { en, bg,
  'faq.items.becomePartner.a': { en, bg, за да научите повече за ползите и процеса на кандидатстване.' },
  'faq.cta.title': { en, bg,
  'faq.cta.subtitle': { en, bg, за да помогнем' },
  'faq.cta.contact': { en, bg,
  'faq.cta.help': { en, bg,

  // Terms of Service page
  'terms.hero.title': { en, bg,
  'terms.hero.subtitle': { en, 2024', bg,
  'terms.sections.acceptance.title': { en, bg,
  'terms.sections.acceptance.content': { en, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.', bg, вие приемате и се съгласявате да бъдете обвързани от условията и разпоредбите на това споразумение. Ако не сте съгласни да спазвате горното, моля не използвайте тази услуга.' },
  'terms.sections.services.title': { en, bg,
  'terms.sections.services.content': { en, hotels, spas, and entertainment venues throughout Bulgaria. The service is provided through our website and mobile applications.', bg, която предлага ексклузивни отстъпки в партньорски локации, включително ресторанти, хотели, спа центрове и места за развлечение в цяла България. Услугата се предоставя чрез нашия уебсайт и мобилни приложения.' },
  'terms.sections.membership.title': { en, bg,
  'terms.sections.membership.content': { en, you must register for an account and select a membership plan. You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account.', bg, трябва да се регистрирате за акаунт и да изберете план за членство. Вие носите отговорност за поддържането на поверителността на информацията за акаунта си и за всички дейности, които се извършват под вашия акаунт.' },
  'terms.sections.payment.title': { en, bg,
  'terms.sections.payment.content': { en, depending on your selected plan. All fees are non-refundable except as required by law. You may cancel your subscription at any time, and your access will continue until the end of your current billing period.', bg, в зависимост от избрания от вас план. Всички такси не подлежат на възстановяване, освен ако законът не изисква друго. Можете да отмените абонамента си по всяко време, а достъпът ви ще продължи до края на текущия период на фактуриране.' },
  'terms.sections.usage.title': { en, bg,
  'terms.sections.usage.content': { en, bg, освен ако нямате Семеен план. Злоупотребата с услугата може да доведе до прекратяване на акаунта ви.' },
  'terms.sections.partners.title': { en, bg,
  'terms.sections.partners.content': { en, bg, предоставени от партньорите. Всички транзакции са между вас и партньорския бизнес.' },
  'terms.sections.privacy.title': { en, bg,
  'terms.sections.privacy.content': { en, which also governs the Site and informs users of our data collection practices.', bg, прегледайте нашата Политика за поверителност, която също управлява сайта и информира потребителите за нашите практики за събиране на данни.' },
  'terms.sections.liability.title': { en, bg,
  'terms.sections.liability.content': { en, incidental, special, consequential, or punitive damages resulting from your use or inability to use the service.', bg, случайни, специални, последващи или наказателни щети, произтичащи от вашата употреба или невъзможност да използвате услугата.' },
  'terms.sections.changes.title': { en, bg,
  'terms.sections.changes.content': { en, bg, като публикуваме новите Условия за ползване на тази страница.' },
  'terms.sections.contact.title': { en, bg,
  'terms.sections.contact.content': { en, please contact us at legal@boomcard.bg.', bg, моля свържете се с нас на legal@boomcard.bg.' },

  // Privacy Policy page
  'privacy.hero.title': { en, bg,
  'privacy.hero.subtitle': { en, 2024', bg,
  'privacy.intro': { en, "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our service.', bg, „наш" или „нас") се ангажира да защитава вашата поверителност. Тази Политика за поверителност обяснява как събираме, използваме, разкриваме и защитаваме вашата информация, когато използвате нашата услуга.' },
  'privacy.sections.collection.title': { en, bg, която събираме' },
  'privacy.sections.collection.personal.title': { en, bg,
  'privacy.sections.collection.personal.content': { en, such as when you create an account, including, email address, phone number, billing information, and address.', bg, която ни предоставяте директно, например когато създавате акаунт, включително: име, имейл адрес, телефонен номер, информация за фактуриране и адрес.' },
  'privacy.sections.collection.usage.title': { en, bg,
  'privacy.sections.collection.usage.content': { en, including, partner locations visited, app usage patterns, and device information.', bg, включително: използвани отстъпки, посетени партньорски локации, модели на използване на приложението и информация за устройството.' },
  'privacy.sections.use.title': { en, bg,
  'privacy.sections.use.items.1': { en, bg,
  'privacy.sections.use.items.2': { en, bg,
  'privacy.sections.use.items.3': { en, bg,
  'privacy.sections.use.items.4': { en, services, and promotional offers', bg, услуги и промоционални оферти' },
  'privacy.sections.use.items.5': { en, bg,
  'privacy.sections.use.items.6': { en, bg,
  'privacy.sections.sharing.title': { en, bg,
  'privacy.sections.sharing.content': { en, trade, or rent your personal information to third parties. We may share your information in the following situations, bg, търгуваме или отдаваме под наем вашата лична информация на трети страни. Можем да споделим вашата информация в следните ситуации:' },
  'privacy.sections.sharing.items.1': { en, bg, когато използвате отстъпки' },
  'privacy.sections.sharing.items.2': { en, bg, които ни помагат да управляваме бизнеса си' },
  'privacy.sections.sharing.items.3': { en, bg,
  'privacy.sections.sharing.items.4': { en, bg,
  'privacy.sections.security.title': { en, bg,
  'privacy.sections.security.content': { en, alteration, disclosure, or destruction. However, no method of transmission over the Internet is 100% secure.', bg, промяна, разкриване или унищожаване. Въпреки това, никой метод на предаване през интернет не е 100% сигурен.' },
  'privacy.sections.rights.title': { en, bg,
  'privacy.sections.rights.content': { en, bg,
  'privacy.sections.rights.items.1': { en, bg,
  'privacy.sections.rights.items.2': { en, bg,
  'privacy.sections.rights.items.3': { en, bg,
  'privacy.sections.rights.items.4': { en, bg,
  'privacy.sections.rights.items.5': { en, bg,
  'privacy.sections.rights.items.6': { en, bg,
  'privacy.sections.cookies.title': { en, bg,
  'privacy.sections.cookies.content': { en, bg, за да следим дейността в нашата услуга и да съхраняваме определена информация. Можете да инструктирате браузъра си да отказва всички бисквитки или да показва кога се изпраща бисквитка.' },
  'privacy.sections.children.title': { en, bg,
  'privacy.sections.children.content': { en, bg,
  'privacy.sections.changes.title': { en, bg,
  'privacy.sections.changes.content': { en, bg, като публикуваме новата Политика за поверителност на тази страница и актуализираме датата „Последна актуализация".' },
  'privacy.sections.contact.title': { en, bg,
  'privacy.sections.contact.content': { en, please contact us at, bg, моля свържете се с нас на:' },

  // Cookie Policy page
  'cookies.hero.title': { en, bg,
  'cookies.hero.subtitle': { en, 2024', bg,
  'cookies.intro': { en, "us", and "our") uses cookies and similar technologies to recognize you when you visit our website and use our mobile applications.', bg, „нас" и „наш") използва бисквитки и подобни технологии, за да ви разпознае, когато посещавате нашия уебсайт и използвате нашите мобилни приложения.' },
  'cookies.sections.what.title': { en, bg,
  'cookies.sections.what.content': { en, or to work more efficiently, as well as to provide reporting information.', bg, които се поставят на вашия компютър или мобилно устройство, когато посещавате уебсайт. Бисквитките се използват широко от собствениците на уебсайтове, за да накарат техните уебсайтове да работят или да работят по-ефективно, както и за предоставяне на информация за отчитане.' },
  'cookies.sections.types.title': { en, bg, които използваме' },
  'cookies.sections.types.essential.title': { en, bg,
  'cookies.sections.types.essential.content': { en, logging in, or filling in forms.', bg, извършени от вас, като задаване на вашите предпочитания за поверителност, влизане или попълване на формуляри.' },
  'cookies.sections.types.performance.title': { en, bg,
  'cookies.sections.types.performance.content': { en, bg, за да можем да измерваме и подобряваме производителността на нашия сайт. Те ни помагат да знаем кои страници са най-популярни и най-малко популярни и да видим как посетителите се движат из сайта.' },
  'cookies.sections.types.functional.title': { en, bg,
  'cookies.sections.types.functional.content': { en, bg, чиито услуги сме добавили към нашите страници.' },
  'cookies.sections.types.targeting.title': { en, bg,
  'cookies.sections.types.targeting.content': { en, bg,
  'cookies.sections.specific.title': { en, bg, които използваме' },
  'cookies.table.name': { en, bg,
  'cookies.table.purpose': { en, bg,
  'cookies.table.expiry': { en, bg,
  'cookies.sections.control.title': { en, bg,
  'cookies.sections.control.content': { en, or to alert you when websites set or access cookies. If you disable or refuse cookies, please note that some parts of this website may become inaccessible or not function properly.', bg, когато уебсайтовете задават или имат достъп до бисквитки. Ако деактивирате или откажете бисквитки, моля, имайте предвид, че някои части от този уебсайт може да станат недостъпни или да не функционират правилно.' },
  'cookies.sections.control.browsers': { en, bg,
  'cookies.sections.thirdparty.title': { en, bg,
  'cookies.sections.thirdparty.content': { en, we may also use various third-party cookies to report usage statistics of the service and deliver advertisements on and through the service.', bg, можем също да използваме различни бисквитки на трети страни, за да отчитаме статистиката за използване на услугата и да доставяме реклами в и чрез услугата.' },
  'cookies.sections.updates.title': { en, bg,
  'cookies.sections.updates.content': { en, legal, or regulatory reasons.', bg, за да отразим промени в бисквитките, които използваме, или поради други оперативни, правни или регулаторни причини.' },
  'cookies.sections.contact.title': { en, bg,
  'cookies.sections.contact.content': { en, please email us at privacy@boomcard.bg.', bg, моля изпратете ни имейл на privacy@boomcard.bg.' },

  // Partner With Us page
  'partnerWithUs.hero.title': { en, bg,
  'partnerWithUs.hero.subtitle': { en, bg,
  'partnerWithUs.benefits.title': { en, bg,
  'partnerWithUs.benefits.customers.title': { en, bg,
  'partnerWithUs.benefits.customers.description': { en, bg, които активно търсят премиум преживявания' },
  'partnerWithUs.benefits.revenue.title': { en, bg,
  'partnerWithUs.benefits.revenue.description': { en, bg,
  'partnerWithUs.benefits.cost.title': { en, bg,
  'partnerWithUs.benefits.cost.description': { en, bg,
  'partnerWithUs.benefits.marketing.title': { en, bg,
  'partnerWithUs.benefits.marketing.description': { en, website, and promotional materials at no extra cost', bg, уебсайт и промоционални материали без допълнителни разходи' },
  'partnerWithUs.benefits.analytics.title': { en, bg,
  'partnerWithUs.benefits.analytics.description': { en, bg,
  'partnerWithUs.benefits.flexible.title': { en, bg,
  'partnerWithUs.benefits.flexible.description': { en, bg,
  'partnerWithUs.howItWorks.title': { en, bg,
  'partnerWithUs.howItWorks.step1.title': { en, bg,
  'partnerWithUs.howItWorks.step1.description': { en, bg,
  'partnerWithUs.howItWorks.step2.title': { en, bg,
  'partnerWithUs.howItWorks.step2.description': { en, bg,
  'partnerWithUs.howItWorks.step3.title': { en, bg,
  'partnerWithUs.howItWorks.step3.description': { en, bg,
  'partnerWithUs.howItWorks.step4.title': { en, bg,
  'partnerWithUs.howItWorks.step4.description': { en, bg,
  'partnerWithUs.form.title': { en, bg,
  'partnerWithUs.form.businessName': { en, bg,
  'partnerWithUs.form.contactName': { en, bg,
  'partnerWithUs.form.email': { en, bg,
  'partnerWithUs.form.phone': { en, bg,
  'partnerWithUs.form.businessType': { en, bg,
  'partnerWithUs.form.selectType': { en, bg,
  'partnerWithUs.form.types.restaurant': { en, bg,
  'partnerWithUs.form.types.hotel': { en, bg,
  'partnerWithUs.form.types.spa': { en, bg,
  'partnerWithUs.form.types.entertainment': { en, bg,
  'partnerWithUs.form.types.retail': { en, bg,
  'partnerWithUs.form.types.other': { en, bg,
  'partnerWithUs.form.location': { en, bg,
  'partnerWithUs.form.website': { en)', bg)' },
  'partnerWithUs.form.message': { en, bg,
  'partnerWithUs.form.submit': { en, bg,
  'partnerWithUs.form.success': { en, bg,
  'partnerWithUs.cta.title': { en, bg,
  'partnerWithUs.cta.subtitle': { en, bg, за да помогне' },

  // Dashboard page
  'dashboard.title': { en, bg,
  'dashboard.description': { en, track partner visits, and manage your BOOM Card membership from your personalized dashboard', bg, проследете посещенията при партньори и управлявайте членството си в BOOM Card от вашето персонализирано табло' },
  'dashboard.nav.home': { en, bg,
  'dashboard.nav.partners': { en, bg,
  'dashboard.nav.plans': { en, bg,
  'dashboard.nav.dashboard': { en, bg,
  'dashboard.hero.memberBadge': { en, bg,
  'dashboard.hero.welcomeBack': { en,', bg,' },
  'dashboard.hero.subtitle': { en,847 this year with BOOM Card. Keep exploring Bulgaria's premium experiences!", bg,847 тази година с BOOM Card. Продължете да изследвате премиум преживяванията в България!' },
  'dashboard.hero.findPartners': { en, bg,
  'dashboard.hero.openApp': { en, bg,
  'dashboard.hero.totalSaved': { en, bg,
  'dashboard.hero.visitsThisYear': { en, bg,
  'dashboard.tabs.overview': { en, bg,
  'dashboard.tabs.activity': { en, bg,
  'dashboard.tabs.favorites': { en, bg,
  'dashboard.tabs.achievements': { en, bg,
  'dashboard.overview.title': { en, bg,
  'dashboard.overview.week': { en, bg,
  'dashboard.overview.month': { en, bg,
  'dashboard.overview.year': { en, bg,
  'dashboard.overview.totalSavedYear': { en, bg,
  'dashboard.overview.averageMonth': { en, bg,
  'dashboard.overview.partnerVisits': { en, bg,
  'dashboard.overview.acrossLocations': { en, bg,
  'dashboard.overview.averageDiscount': { en, bg,
  'dashboard.overview.upToAvailable': { en, bg,
  'dashboard.overview.achievements': { en, bg,
  'dashboard.overview.moreToUnlock': { en, bg,
  'dashboard.overview.vsLastMonth': { en, bg,
  'dashboard.overview.thisWeek': { en, bg,
  'dashboard.overview.premium': { en, bg,
  'dashboard.overview.newAchievements': { en, bg,
  'dashboard.card.title': { en, bg,
  'dashboard.card.refresh': { en, bg,
  'dashboard.card.premiumMember': { en, bg,
  'dashboard.card.memberId': { en, bg,
  'dashboard.card.validUntil': { en, bg,
  'dashboard.card.qrCodeText': { en, bg,
  'dashboard.card.openInApp': { en, bg,
  'dashboard.highlights.title': { en, bg,
  'dashboard.highlights.bestMonth': { en, bg,
  'dashboard.highlights.highestSavings': { en, bg,
  'dashboard.highlights.saved': { en, bg,
  'dashboard.highlights.newDiscovery': { en, bg,
  'dashboard.highlights.newPartners': { en, bg,
  'dashboard.highlights.locations': { en, bg,
  'dashboard.highlights.vipProgress': { en, bg,
  'dashboard.highlights.towardsVip': { en, bg,
  'dashboard.highlights.complete': { en, bg,
  'dashboard.activity.title': { en, bg,
  'dashboard.activity.saved': { en, bg,
  'dashboard.favorites.title': { en, bg,
  'dashboard.favorites.visits': { en, bg,
  'dashboard.favorites.totalSaved': { en, bg,
  'dashboard.favorites.visitAgain': { en, bg,
  'dashboard.achievements.title': { en, bg,
  'dashboard.achievements.earned': { en, bg,
  'dashboard.achievements.progress': { en, bg,
  'dashboard.achievements.savingsChampion': { en, bg,
  'dashboard.achievements.savedOver1000': { en,000', bg,000' },
  'dashboard.achievements.explorer': { en, bg,
  'dashboard.achievements.visited50Partners': { en, bg,
  'dashboard.achievements.vipMember': { en, bg,
  'dashboard.achievements.reachVipStatus': { en, bg,
  'dashboard.achievements.socialSaver': { en, bg,
  'dashboard.achievements.refer10Friends': { en, bg,

  // Profile page
  'profile.title': { en, bg,
  'profile.description': { en, bg,
  'profile.nav.home': { en, bg,
  'profile.nav.partners': { en, bg,
  'profile.nav.plans': { en, bg,
  'profile.nav.dashboard': { en, bg,
  'profile.nav.profile': { en, bg,
  'profile.hero.premiumMember': { en, bg,
  'profile.hero.member': { en, bg,
  'profile.hero.editProfile': { en, bg,
  'profile.hero.saveChanges': { en, bg,
  'profile.sidebar.personalInfo': { en, bg,
  'profile.sidebar.membership': { en, bg,
  'profile.sidebar.preferences': { en, bg,
  'profile.sidebar.security': { en, bg,
  'profile.sidebar.billing': { en, bg,
  'profile.sidebar.reviews': { en, bg,
  'profile.personal.title': { en, bg,
  'profile.personal.firstName': { en, bg,
  'profile.personal.lastName': { en, bg,
  'profile.personal.email': { en, bg,
  'profile.personal.phone': { en, bg,
  'profile.personal.birthDate': { en, bg,
  'profile.personal.address': { en, bg,
  'profile.personal.saveChanges': { en, bg,
  'profile.personal.cancel': { en, bg,
  'profile.membership.title': { en, bg,
  'profile.membership.membership': { en, bg,
  'profile.membership.memberSince': { en, bg,
  'profile.membership.cardNumber': { en, bg,
  'profile.membership.validUntil': { en, bg,
  'profile.membership.perMonth': { en, bg,
  'profile.membership.totalSaved': { en, bg,
  'profile.membership.partnerVisits': { en, bg,
  'profile.membership.avgDiscount': { en, bg,
  'profile.membership.upgradeToVip': { en, bg,
  'profile.preferences.title': { en, bg,
  'profile.preferences.notifications': { en, bg,
  'profile.preferences.emailNotifications': { en, bg,
  'profile.preferences.smsNotifications': { en, bg,
  'profile.preferences.newsletterSubscription': { en, bg,
  'profile.preferences.partnerUpdates': { en, bg,
  'profile.preferences.regionalSettings': { en, bg,
  'profile.preferences.language': { en, bg,
  'profile.preferences.currency': { en, bg,
  'profile.preferences.english': { en, bg,
  'profile.preferences.bulgarian': { en, bg,
  'profile.security.title': { en, bg,
  'profile.security.twoFactorWarning': { en, bg,
  'profile.security.changePassword': { en, bg,
  'profile.security.currentPassword': { en, bg,
  'profile.security.newPassword': { en, bg,
  'profile.security.confirmNewPassword': { en, bg,
  'profile.security.updatePassword': { en, bg,
  'profile.security.loginHistory': { en, bg,
  'profile.billing.title': { en, bg,
  'profile.billing.paymentMethod': { en, bg,
  'profile.billing.expires': { en, bg,
  'profile.billing.update': { en, bg,
  'profile.billing.billingHistory': { en, bg,
  'profile.billing.premiumMembership': { en, bg,
  'profile.billing.paid': { en, bg,
  'profile.billing.download': { en, bg,
  'profile.reviews.title': { en, bg,
  'profile.reviews.yourReviews': { en, bg,
  'profile.reviews.writeReview': { en, bg,
  'profile.reviews.writeNewReview': { en, bg,
  'profile.reviews.selectPartner': { en, bg,
  'profile.reviews.choosePlaceholder': { en, bg,
  'profile.reviews.rating': { en, bg,
  'profile.reviews.yourReview': { en, bg,
  'profile.reviews.reviewPlaceholder': { en, bg,
  'profile.reviews.submitReview': { en, bg,
  'profile.reviews.cancel': { en, bg,

  // Footer
  'footer.tagline': { en, bg,
  'footer.quickLinks': { en, bg,
  'footer.support': { en, bg,
  'footer.contact': { en, bg,
  'footer.home': { en, bg,
  'footer.partners': { en, bg,
  'footer.membershipPlans': { en, bg,
  'footer.memberDashboard': { en, bg,
  'footer.howItWorks': { en, bg,
  'footer.helpCenter': { en, bg,
  'footer.contactUs': { en, bg,
  'footer.faqs': { en, bg,
  'footer.partnerWithUs': { en, bg,
  'footer.termsConditions': { en, bg,
  'footer.copyright': { en, bg,
  'footer.privacyPolicy': { en, bg,
  'footer.termsOfService': { en, bg,
  'footer.cookiePolicy': { en, bg,

  // Partners page
  'partners.title': { en, bg,
  'partners.description': { en, bg, предлагащи изключителни отстъпки в цяла България' },
  'partners.nav.home': { en, bg,
  'partners.nav.partners': { en, bg,
  'partners.nav.plans': { en, bg,
  'partners.nav.dashboard': { en, bg,
  'partners.nav.getStarted': { en, bg,
  'partners.hero.badge': { en, bg,
  'partners.hero.title1': { en, bg,
  'partners.hero.title2': { en, bg,
  'partners.hero.subtitle': { en, hotels, spas, and entertainment venues', bg, хотели, спа центрове и места за забавление в България' },
  'partners.hero.activePartners': { en, bg,
  'partners.hero.cities': { en, bg,
  'partners.hero.maxDiscount': { en, bg,
  'partners.categories.title': { en, bg,
  'partners.categories.allPartners': { en, bg,
  'partners.categories.fineDining': { en, bg,
  'partners.categories.luxuryHotels': { en, bg,
  'partners.categories.wellness': { en, bg,
  'partners.categories.entertainment': { en, bg,
  'partners.categories.fineDiningDesc': { en, bg,
  'partners.categories.luxuryHotelsDesc': { en, bg,
  'partners.categories.wellnessDesc': { en, bg,
  'partners.categories.entertainmentDesc': { en, venues, and entertainment experiences', bg, места и развлекателни преживявания' },
  'partners.categories.upTo': { en, bg,
  'partners.featured.title': { en, bg,
  'partners.featured.viewDetails': { en, bg,
  'partners.featured.rating': { en, bg,
  'partners.search.placeholder': { en, bg,
  'partners.search.button': { en, bg,
  'partners.partners': { en, bg,
  'partners.categories.subtitle': { en, bg, което търсите в нашите подбрани категории' },
  'partners.categories.explorePartners': { en, bg,
  'partners.featured.subtitle': { en, bg,
  'partners.featured.description': { en, bg, предлагащи най-добрите преживявания в цяла България' },
  'partners.cta.title': { en, bg,
  'partners.cta.subtitle': { en,000+ members already enjoying exclusive discounts at Bulgaria\'s finest establishments', bg,000+ членове, които вече се наслаждават на ексклузивни отстъпки в най-добрите заведения в България' },
  'partners.cta.choosePlan': { en, bg,
  'partners.cta.downloadApp': { en, bg,

  // Demo page
  'demo.title': { en, bg,
  'demo.description': { en, bg, за да видите как BOOM Card ви помага да спестявате за премиум преживявания' },
  'demo.hero.title': { en, bg,
  'demo.hero.subtitle': { en, bg,
  'demo.interactive.badge': { en, bg,
  'demo.interactive.title': { en, bg,
  'demo.interactive.subtitle': { en, bg, за да видите всяка стъпка от използването на BOOM Card' },
  'demo.interactive.step': { en, bg,
  'demo.interactive.previous': { en, bg,
  'demo.interactive.next': { en, bg,
  'demo.step1.title': { en, bg,
  'demo.step1.description': { en, location, or discount amount to find exactly what you\'re looking for.', bg, местоположение или размер на отстъпката, за да намерите точно това, което търсите.' },
  'demo.step2.title': { en, bg,
  'demo.step2.description': { en, bg, за да приложи вашата ексклузивна отстъпка.' },
  'demo.step3.title': { en, bg,
  'demo.step3.description': { en, no complicated processes - just instant savings!', bg, без сложни процеси - само мигновени спестявания!' },
  'demo.step4.title': { en, bg,
  'demo.step4.description': { en, favorite partners, and achievements in your personal dashboard. Watch your savings grow!', bg, любимите партньори и постиженията в личното си табло. Наблюдавайте как спестяванията ви растат!' },
  'demo.features.title': { en, bg,
  'demo.features.instant.title': { en, bg,
  'demo.features.instant.description': { en, no vouchers - just show your QR code and save', bg, без ваучери - просто покажете QR кода си и спестете' },
  'demo.features.secure.title': { en, bg,
  'demo.features.secure.description': { en, bg,
  'demo.features.everywhere.title': { en, bg,
  'demo.features.everywhere.description': { en, bg,
  'demo.video.title': { en, bg,
  'demo.video.subtitle': { en, bg,
  'demo.video.placeholder': { en, bg,
  'demo.cta.title': { en, bg,
  'demo.cta.subtitle': { en, bg, които вече се наслаждават на ексклузивни отстъпки' },
  'demo.cta.getStarted': { en, bg,
  'demo.cta.explorePartners': { en, bg,

  // Plans/Subscriptions page
  'plans.title': { en, bg,
  'plans.description': { en, bg, за да отключите ексклузивни отстъпки в цяла България' },
  'plans.nav.home': { en, bg,
  'plans.nav.partners': { en, bg,
  'plans.nav.plans': { en, bg,
  'plans.nav.dashboard': { en, bg,
  'plans.nav.profile': { en, bg,
  'plans.nav.getStarted': { en, bg,
  'plans.hero.title1': { en, bg,
  'plans.hero.title2': { en, bg,
  'plans.hero.subtitle': { en, bg,
  'plans.features.partnerAccess': { en, bg,
  'plans.features.averageDiscount': { en, bg,
  'plans.features.mobileApp': { en, bg,
  'plans.features.customerSupport': { en, bg,
  'plans.features.prioritySupport': { en, bg,
  'plans.features.conciergeSupport': { en, bg,
  'plans.features.restaurantReservations': { en, bg,
  'plans.features.priorityReservations': { en, bg,
  'plans.features.premiumDining': { en, bg,
  'plans.features.allDining': { en, bg,
  'plans.features.luxuryHotel': { en, bg,
  'plans.features.fourStarHotel': { en, bg,
  'plans.features.fiveStarHotel': { en, bg,
  'plans.features.vipEvents': { en, bg,
  'plans.features.vipEventsAccess': { en, bg,
  'plans.billing.monthly': { en, bg,
  'plans.billing.yearly': { en, bg,
  'plans.billing.savePercent': { en, bg,
  'plans.billing.perMonth': { en, bg,
  'plans.billing.perYear': { en, bg,
  'plans.billing.billedMonthly': { en, bg,
  'plans.billing.billedYearly': { en, bg,
  'plans.cta.selectPlan': { en, bg,
  'plans.cta.currentPlan': { en, bg,
  'plans.popularBadge': { en, bg,
  'plans.comparison.title': { en, bg,
  'plans.comparison.partnerNetwork': { en, bg,
  'plans.comparison.discountRange': { en, bg,
  'plans.comparison.mobileApp': { en, bg,
  'plans.comparison.support': { en, bg,
  'plans.comparison.reservations': { en, bg,
  'plans.comparison.premiumDining': { en, bg,
  'plans.comparison.hotelAccess': { en, bg,
  'plans.comparison.vipEvents': { en, bg,
  'plans.comparison.savingsPotential': { en, bg,
  'plans.faq.title': { en, bg,
  'plans.mostPopular': { en, bg,
  'plans.popular': { en, bg,
  'plans.comparison.badge': { en, bg,
  'plans.comparison.title': { en, bg,
  'plans.comparison.featuresAndBenefits': { en, bg,
  'plans.essential.savings': { en, bg,
  'plans.premium.savings': { en, bg,
  'plans.vip.savings': { en,200+ saved annually', bg,200+ спестени годишно' },
  'plans.features.access100Partners': { en, bg,
  'plans.features.access250Partners': { en, bg,
  'plans.features.access375Partners': { en, bg,
  'plans.features.discount10to15': { en, bg,
  'plans.features.discount15to25': { en, bg,
  'plans.features.discount20to40': { en, bg,
  'plans.features.mobileApp': { en, bg,
  'plans.features.basicSupport': { en, bg,
  'plans.features.prioritySupport': { en, bg,
  'plans.features.conciergeSupport': { en, bg,
  'plans.features.restaurantReservations': { en, bg,
  'plans.features.priorityReservations': { en, bg,
  'plans.features.premiumDining': { en, bg,
  'plans.features.allPremiumDining': { en, bg,
  'plans.features.luxuryHotelAccess': { en, bg,
  'plans.features.fourStarHotels': { en, bg,
  'plans.features.fiveStarHotels': { en, bg,
  'plans.features.vipEvents': { en, bg,
  'plans.features.vipEventsExperiences': { en, bg,
  'plans.comparison.basicSupport': { en, bg,
  'plans.comparison.prioritySupport': { en, bg,
  'plans.comparison.conciergeSupport': { en, bg,
  'plans.comparison.priorityText': { en, bg,
  'plans.comparison.fourStar': { en, bg,
  'plans.comparison.fiveStar': { en, bg,
  'plans.comparison.savingsPotential': { en, bg,
  'plans.faq.changePlan.question': { en, bg,
  'plans.faq.changePlan.answer': { en, and we\'ll prorate any billing differences.', bg,
  'plans.faq.satisfaction.question': { en, bg, ако не съм доволен?' },
  'plans.faq.satisfaction.answer': { en, we\'ll refund your membership fee.', bg, ще върнем членската ви такса.' },
  'plans.faq.howToUse.question': { en, bg,
  'plans.faq.howToUse.answer': { en, bg,
  'plans.cta.title': { en, bg,
  'plans.cta.subtitle': { en,000+ members already enjoying exclusive discounts at Bulgaria\'s finest establishments', bg,000+ членове, които вече се наслаждават на ексклузивни отстъпки в най-добрите заведения в България' },
  'plans.cta.startMembership': { en, bg,
  'plans.cta.downloadApp': { en, bg,

  // Help Center
  'help.title': { en, bg,
  'help.description': { en, bg,
  'help.hero.title': { en, bg,
  'help.hero.subtitle': { en, bg,
  'help.searchPlaceholder': { en, bg,
  'help.categories.all': { en, bg,
  'help.categories.account': { en, bg,
  'help.categories.billing': { en, bg,
  'help.categories.usage': { en, bg,
  'help.categories.partners': { en, bg,
  'help.categories.technical': { en, bg,
  'help.articles.resetPassword.title': { en, bg,
  'help.articles.resetPassword.content': { en, bg,
  'help.articles.changeSubscription.title': { en, bg,
  'help.articles.changeSubscription.content': { en, bg,
  'help.articles.useQR.title': { en, bg,
  'help.articles.useQR.content': { en, tap on "My Card" to display your QR code. Show it to the merchant at checkout.', bg, докоснете "Моята карта", за да покажете вашия QR код. Покажете го на търговеца при плащане.' },
  'help.articles.findPartners.title': { en, bg,
  'help.articles.findPartners.content': { en, bg,
  'help.articles.appNotWorking.title': { en, bg,
  'help.articles.appNotWorking.content': { en, contact support.', bg, свържете се с поддръжката.' },
  'help.articles.cancelSubscription.title': { en, bg,
  'help.articles.cancelSubscription.content': { en, bg,
  'help.popular': { en, bg,
  'help.readMore': { en, bg,
  'help.noResults': { en, bg,
  'help.contact.title': { en, bg,
  'help.contact.subtitle': { en, bg, за да ви помогне' },
  'help.contact.email': { en, bg,
  'help.contact.phone': { en, bg,
  'help.contact.hours': { en, bg,
  'nav.help': { en, bg,
  'nav.howItWorks': { en, bg,

  // How It Works
  'howItWorks.title': { en, bg,
  'howItWorks.description': { en, bg,
  'howItWorks.hero.title': { en, bg,
  'howItWorks.hero.subtitle': { en, bg,
  'howItWorks.steps.signUp.title': { en, bg,
  'howItWorks.steps.signUp.description': { en, Premium, or VIP membership plans.', bg, Premium или VIP членски планове.' },
  'howItWorks.steps.getCard.title': { en, bg,
  'howItWorks.steps.getCard.description': { en, bg,
  'howItWorks.steps.browse.title': { en, bg,
  'howItWorks.steps.browse.description': { en, bg,
  'howItWorks.steps.save.title': { en, bg,
  'howItWorks.steps.save.description': { en, bg,
  'howItWorks.benefits.title': { en, bg,
  'howItWorks.benefits.savings.title': { en, bg,
  'howItWorks.benefits.savings.description': { en, bg,
  'howItWorks.benefits.digital.title': { en, bg,
  'howItWorks.benefits.digital.description': { en, bg,
  'howItWorks.benefits.instant.title': { en, bg,
  'howItWorks.benefits.instant.description': { en, bg,
  'howItWorks.cta.title': { en, bg,
  'howItWorks.cta.subtitle': { en, bg, които се наслаждават на ексклузивни отстъпки' },
  'howItWorks.cta.button': { en, bg,
  'footer.howItWorks': { en, bg,

  // Authentication
  'auth.login': { en, bg,
  'auth.register': { en, bg,
  'auth.logout': { en, bg,
  'auth.email': { en, bg,
  'auth.password': { en, bg,
  'auth.firstName': { en, bg,
  'auth.lastName': { en, bg,
  'auth.confirmPassword': { en, bg,
  'auth.loginButton': { en, bg,
  'auth.registerButton': { en, bg,
  'auth.forgotPassword': { en, bg,
  'auth.noAccount': { en, bg,
  'auth.haveAccount': { en, bg,
  'auth.signUp': { en, bg,
  'auth.loginTitle': { en, bg,
  'auth.loginDescription': { en, bg,
  'auth.registerTitle': { en, bg,
  'auth.registerDescription': { en, bg,
  'auth.rememberMe': { en, bg,
  'auth.loggingIn': { en, bg,
  'auth.creatingAccount': { en, bg,
  'auth.backToHome': { en, bg,
  'auth.byLoggingIn': { en, you agree to our', bg, вие се съгласявате с нашите' },
  'auth.and': { en, bg,
  'auth.passwordMismatch': { en, bg,
  'auth.passwordTooShort': { en, bg,
  'auth.passwordHint': { en, bg,
  'auth.agreeToTerms': { en, bg,
};

const LanguageContext = createContext(undefined);

export function LanguageProvider({ children }: { children) {
  const [language, setLanguage] = useState('en');
  
  // Load language from localStorage on mount
  React.useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'bg')) {
      setLanguage(savedLanguage);
    }
  }, []);
  
  // Save language to localStorage when it changes
  const handleSetLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };
  
  const t = (key) => {
    return translations[key]?.[language] || key;
  };
  
  return (
    
      {children}
    
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}